title:              Chenyu Wang
email:              chyuwang@umich.edu
description:        Academic blog
author:             Chenyu Wang
baseurl:            ""
url:                "https://SALTCOFFEEEE.github.io"

# Social Profiles
twitter_username:   
github_username:    
facebook_username:  
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   G-RBZW7PJFPB # out your google-analytics code

# Build settings
markdown:  kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-katex
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
